version: 2
jobs:
  build:
    machine:
       environment: 
       image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
